testurl = 'https://dev.wambiapp.com/'
samlurl = "samlwambi.com"
usrname = "W00047SE"
pword = "AceWambi03"
searchwith = 'Edna Wambi-Galindo'
pytest_plugins = 'allure.pytest_plugin'
usrnameSA = "W00047SA"
patientPortalURL = 'https://portaldev.wambiapp.com/'
patientPortalLocation = 'https://portaldev.wambiapp.com/en/location'
patientPortalLoginpage = 'https://portaldev.wambiapp.com/en/login'
teamMemberSearch = 'https://portaldev.wambiapp.com/en/employee'
responsePage = 'https://portaldev.wambiapp.com/en/survey?employeeId=177884&unitId=10'
getOTP = 'https://portaldev.wambiapp.com/api/utilities/getOTPToken?patientId=265&secret=pineapples'
getOTPAdmUser = 'https://portaldev.wambiapp.com/api/utilities/getOTPToken?patientId=266&secret=pineapples'
empUser = "W00047em"
perksearchText = "W00055NURSE"
h = "rds-dev-test.wambiapp.com"
u = "asad.faheem"
p = "53hnE!m4DePM5"
d = 'concept'
wambiNewURL = 'https://dev-w4.wambiapp.com/auth/login'
myPortalUserid = 'Courtney'
myPortalPwd = 'Test!123'
multiplePortalUserid = 'AutomationQA'
multiplePortalPwd = 'Test123!!'
