Ambassadors = "//a[contains(text(),'Ambassadors')]"
addAmbassador = "//a[contains(text(),'Add Ambassador')]"
clickFacilityOption = "//span[@id='select2-fac_id-container']"
selectFacilities = "//li[@class='select2-results__option select2-results__option--highlighted']"
name = "//input[@id='fname']"
submit = "//button[@type='submit']"
searchambId = "//input[@placeholder='Search']"
search = "//button[contains(text(),'Search')]"
searchResult = "//html/body/div[2]/div/div[2]/div/div/div[1]/form/div[4]/table/tbody/tr[1]/td[3]"
