awardsTab = "//a[contains(text(), 'Awards')]"
dateTab = "//span[contains(@class,'date_range')]"
ActionTab = "//div[contains(text(), 'Actions')]"
dateValue = "//html/body/div[2]/div/div/div/div/form/div[4]/table/tbody/tr[2]/td[13]"
addAwards = "//a[contains(text(),'Post Award')]"
clickFacilities = "//html/body/div[2]/div/div/div/div[1]/form/div[1]/span/span[1]/span/span[2]"
selectFacilities = "//li[@class='select2-results__option']"
specifyDetails = "//input[@placeholder = ' Specify details']"
submit = "//button[@type='submit']"
searchText = "//input[@class = 'form-control search']"
searchResult = "//html/body/div[2]/div/div/div/div/form/div[4]/table/tbody/tr[1]/td[7]/span"
clickAwardType="//html/body/div[2]/div/div/div/div[1]/form/div[5]/span/span[1]/span/span[2]"
selectAward = "//li[@class='select2-results__option select2-results__option--highlighted']"
IndividualAward = "//span[contains(text(),'Individual Award')]"
selIndividual = "//html/body/div[2]/div/div/div/div[2]/form/div[1]/span/span[1]/span/ul/li/input"
selEmployee ="/html/body/div[2]/div/div/div/div[2]/form/div[2]/span/span[1]/span/span[2]"
selBadge = "//html/body/div[2]/div/div/div/div[2]/form/div[5]/span/span[1]/span/span[2]"
selTimePeriod ="//html/body/div[2]/div/div/div/div[2]/form/div[4]/span/span[1]/span/span[2]"

