loginbtn = "//button[contains(text(),'Log In')]"
profileIcon = "//div[@id ='profile-icon']"
collectPatientGratitude = "//span[contains(text(),'Collect Patient Gratitude')]"
locCount = "//div[@id = 'location-tile']"
selLocation = "//span[contains(text(),'ACME Health Group')]"
NEXT = "//button[contains(text(),'NEXT')]"
whoWouldyouText = "//span[contains(text(),'Who would you')]"
liketoRecognizeText = "//span[contains(text(),'like to recognize?')]"
selectPortal = "//span[contains(text(),'Select a portal:')]"
clickPortal = "//span[contains(text(),'Favicon Air Clinic')]"
continuebtn = "//button[contains(text(),'Continue')]"
selLocation1 = "//span[contains(text(),'Indy North (Hospital)')]"
