employeesTab = "//a[contains(text(), 'Employees')]"
excelButton = "//span[contains(text(), 'Excel')]"
addEmployeesTab = "//a[contains(text(), 'Add Employee')]"
selectUserType = "//select[@id = 'etid']"
selectFacilities = "//select[@id = 'fac_ids']"
clinicOption = "//input[@class = 'select2-search__field']"
employeeId = "//input[@id = 'clockid']"
fName = "//input[@name = 'firstname']"
lName = "//input[@name = 'lastname']"
displayname = "//input[@name = 'display_name']"
submitButtonemployeePage = "//button[@type='submit']"
searchNewEmployee = "//input[@name='key']"
searchSubmit = "//button[@id='search-submit']"
checkEmployee = "//html/body/div[2]/div/div/div[1]/div[1]/form/div[5]/table/tbody/tr[1]/td[10]"


