postPerkbutton = "//a[contains(text(),' Post Perk')]"
perkalertemailbutton = "//a[contains(text(),' Perk Alert Email')]"
giftCards = "//div[@class='gift-card']"
editIcon = "//a[@class='btn btn-primary btn-link']"
deleteIcon = "//form[@class='ajax-delete2']"
cancelButton = "//button[@class='cancel btn btn-lg btn-default']"
deleteButton = "//button[contains(text(),'Yes, delete it!')]"
perksHistory = "//a[contains(text(),'Perk History')]"
searchtext = "//input[@placeholder='Search']"
searchbtn = "//button[contains(text(),'Search')]"
verSearchres = "//html/body/div[2]/div/div[1]/div/div/div/form/div[4]/table/tbody/tr[1]/td[4]"
