selectNurse = "//span[contains(text(),'Amanda T')]"
selectUnit_Dept = "//li[@class = 'Dropdown__StyledOption-sc-1xl7l7e-3 gzncKN']"
textareaInput = "//textarea[@class = 'Textarea__StyledTextarea-sc-2awjro-0 fcRhGy DoBetter__CommentInput-koqxqr-3 cjgEwU']"
skipButton = "//button[contains(text(),'SKIP')]"
textareaNext = "//textarea[@class ='Textarea__StyledTextarea-sc-2awjro-0 fcRhGy']"
nominateNursetext = "//span[contains(text(),'Nominate this nurse')]"
fName = "//input[@id ='First Name']"
lName = "//input[@id = 'Last Name']"
submit = "//button[contains(text(),'SUBMIT')]"
selectanyUnit = "//li[contains(text(),'ALC Pharmacy')]"
phone ="//input[@id = 'Phone']"
Next ="//button[contains(text(),'NEXT')]"
gratitudeTextarea ="//textarea[@id ='gratitude']"
nominate ="//button[contains(text(),'NOMINATE')]"
