selectNurse = "//span[contains(text(),'Wambi Super Admin Edna')]"
clickClinic = "//li[@class = 'Dropdown__StyledOption-sc-1xl7l7e-3 fTnZGf']"
selectClinic = "//li[@class = 'Dropdown__StyledOption-sc-1xl7l7e-3 jxlcUz']"
textareaInput = "//textarea[@class = 'Textarea__StyledTextarea-sc-2awjro-0 fcRhGy DoBetter__CommentInput-koqxqr-3 cjgEwU']"
skipButton = "//button[contains(text(),'SKIP')]"
textareaNext = "//textarea[@class ='Textarea__StyledTextarea-sc-2awjro-0 fcRhGy']"
nominateNursetext = "//span[contains(text(),'Nominate this nurse')]"
fName = "//input[@id ='First Name']"
lName = "//input[@id = 'Last Name']"
submit = "//button[contains(text(),'SUBMIT')]"
selectanyUnit = "//li[contains(text(),'I don't know')]"
phone ="//input[@id = 'Phone']"
Next ="//button[contains(text(),'NEXT')]"
gratitudeTextarea ="//textarea[@id ='gratitude']"
nominate ="//button[contains(text(),'NOMINATE')]"
enterText = "//textarea[@id='daisy-comment-text-area']"
enterPhone = "//input[@id='Phone']"
