jobType = "//div[@class='FilterButton__StyledDivContainer-t7pfx8-2 dciseR']"
jobTypeList = "//div[@class='Dropdown__StyledDropDown-zvjhbr-0 jfddsa']"
searchbyJobType = "//input[@placeholder='Search']"
filterBySearchText = "//div[@class = 'Dropdown__StyledSearchInput-zvjhbr-1 hCFmcY']"
selectedJobType = "//li[@class='Dropdown__StyledOption-sc-1xl7l7e-3 jxlcUz']"
closeJobType = "//div[@class='SearchEmployee__StyledIcon-sc-1k8gk9z-3 fnnALE']"
searchbyPerson = "//input[@placeholder = 'Who would you like to recognize?']"
jobTyperesult = "//button[@class='SearchEmployee__StyledBadge-sc-1k8gk9z-2 eDlcuP']"
submitbtn = "//button[contains(text(),'SUBMIT')]"
