jobType = "//div[@class='FilterButton__StyledDivContainer-t7pfx8-2 dciseR']"
jobTypeList = "//div[@class='Dropdown__StyledDropDown-zvjhbr-0 jfddsa']"
searchbyJobType = "//input[@placeholder='Search']"
filterBySearchText = "//div[@class = 'Dropdown__StyledSearchInput-zvjhbr-1 hCFmcY']"
selectedJobType = "//li[@class='Dropdown__StyledOption-sc-1xl7l7e-3 jxlcUz']"
closeJobType = "//div[@class='SearchPerson__StyledIcon-sc-2pwtdo-3 ggEkpg']"
searchbyPerson = "//input[@placeholder = 'Who would you like to recognize?']"
jobTyperesult = "//button[@class='SearchPerson__StyledBadge-sc-2pwtdo-2 bFHaFD']"
submitbtn = "//button[contains(text(),'SUBMIT')]"
