Unit = "//button[@type='units']"
unitList = "//div[@class='SearchPerson__StyledIcon-sc-2pwtdo-3 bgzlxA']"
searchUnits ="//input[@placeholder='Search']"
filterbySearchUnits = "//li[@class='Dropdown__StyledOption-sc-1xl7l7e-3 jxlcUz']"
selectedUnit = "//button[contains(text(),'ALC Maternity')]"
resultList = "//ul[@class='SearchPerson__StyledUl-sc-2pwtdo-4 kUPrGN']"
closeUnitList = "//div[@class='SearchEmployee__StyledIcon-sc-1k8gk9z-3 oIXKM']"
replacedUnit = "//button[contains(text(),'ALC Critical Care')]"
