enterComments = "//textarea[@label='Comment']"
textAreaElem = "textarea"
toggleContactMe = "//html/body/div/main/section/section/form/div/div[1]/label/span"
firstName = "//input[@id='First Name']"
lastName = "//input[@id = 'Last Name']"
email = "input"