submitLocation = "//button[@id='btnsubmit']"
personProfile = "//div[@class='col-lg-2 col-md-3 col-sm-4 col-xs-4 mix 4']"
beginReview = "//button[@class='confirm']"
surveyAnswers = "//html/body/div[3]/ul[2]/li[1]/img"
surveyAnswers2 = "/html/body/div[3]/ul[2]/li[2]/img"
surveyAnswers3 = "/html/body/div[3]/ul[2]/li[3]/img"
surveyAnswers4 = "/html/body/div[3]/ul[2]/li[4]/img"
surveyAnswers5 = "/html/body/div[3]/ul[2]/li[5]/img"
commentBubbleSection = "//textarea[@name='comment']"
