addPost = "//a[contains(text(),'Add Post')]"
title = "//input[@placeholder = 'Enter title']"
selFacility = "//li[contains(text(),'Delta Harbor Health')]"
content = "//div[@class='note-editable panel-body']"
inputSearch = "//input[@placeholder='Search']"
srchButton = "//button[contains(text(),'Search')]"
resultText = "//a[@class = 'link-newsfeed']"
