userImage = "//div[@class = 'circle-img']"
userName = "//a[@href = 'https://dev.wambiapp.com/employee/settings']"
bioInfoText = "//input[@name='bio']"
sbmtProfile = "//button[@type='submit']"
bioInfoPlaceholder = "//input[@placeholder ='Sample text: 15 years as a Registered Nurse. Enjoy reading Harry Potter.']"
